- hosts: ec2-3-143-251-42.us-east-2.compute.amazonaws.com #host da máquina na AWS
  gather_facts: yes
  become_user: ubuntu
  vars_files:
    - ./vars.yml
  tasks:
   - name: Atualiza o repositório do Composer 2 #utiliza a versão na pasta /var/www/html
     shell: php /var/www/html/composer.phar require --no-update mediawiki/chameleon-skin:~3.0 -n
     become: yes
   - name: Instala o Chameleon usando o Composer 2
     shell: php composer.phar update mediawiki/chameleon-skin --no-dev -o -n
     become: yes
