- hosts: ec2-3-143-251-42.us-east-2.compute.amazonaws.com #host da máquina na AWS
  gather_facts: yes
  become_user: ubuntu
  vars_files:
    - ./vars.yml
  tasks:
   - name: Baixa o pacote tar.gz do Debug Mode
     shell: wget https://extdist.wmflabs.org/dist/extensions/DebugMode-REL1_35-bc39d3c.tar.gz -P /tmp/
     become: yes
   - name: Extrai o Debug Mode para a pasta extensions do MediaWiki
     shell: tar -xvzf /tmp/DebugMode-REL1_35-bc39d3c.tar.gz -C /var/www/html/extensions/
     become: yes
   - name: Remove o pacote tar.gz do Debug Mode
     shell: rm /tmp/DebugMode-REL1_35-bc39d3c.tar.gz
     become: yes
   - name: Modidifica o LocalSettings.php para incluir a nova extensão [1/2]
     shell: echo '#Debug Mode' >> /var/www/html/LocalSettings.php
     become: yes
   - name: Modidifica o LocalSettings.php para incluir a nova extensão [2/2]
     shell: echo 'require_once "$IP/extensions/DebugMode/DebugMode.php";' >> /var/www/html/LocalSettings.php
     become: yes
   - name: Clona o repositório Git do EmbedVideo na pasta extensions do MediaWiki
     shell: git clone https://gitlab.com/hydrawiki/extensions/EmbedVideo.git /var/www/html/extensions/EmbedVideo
     become: yes
   - name: Modidifica o LocalSettings.php para incluir a nova extensão [1/2]
     shell: echo '#EmbedVideo' >> /var/www/html/LocalSettings.php
     become: yes
   - name: Modidifica o LocalSettings.php para incluir a nova extensão [2/2]
     shell: echo 'wfLoadExtension("EmbedVideo");' >> /var/www/html/LocalSettings.php
     become: yes
   - name: Baixa o pacote tar.gz do Head Script
     shell: wget https://extdist.wmflabs.org/dist/extensions/HeadScript-REL1_35-f8245e3.tar.gz -P /tmp/
     become: yes
   - name: Extrai o Debug Mode para a pasta extensions do MediaWiki
     shell: tar -xvzf /tmp/HeadScript-REL1_35-f8245e3.tar.gz -C /var/www/html/extensions/
     become: yes
   - name: Remove o pacote tar.gz do Debug Mode
     shell: rm /tmp/HeadScript-REL1_35-f8245e3.tar.gz
     become: yes
   - name: Modidifica o LocalSettings.php para incluir a nova extensão [1/2]
     shell: echo '#HeadScript' >> /var/www/html/LocalSettings.php
     become: yes
   - name: Modidifica o LocalSettings.php para incluir a nova extensão [2/2]
     shell: echo 'wfLoadExtension( 'HeadScript' );' >> /var/www/html/LocalSettings.php
     become: yes
   - name: Clona o repositório Git do iFrame na pasta extensions do MediaWiki
     shell: git clone https://github.com/sigbertklinke/Iframe /var/www/html/extensions/iFrame
     become: yes
   - name: Modidifica o LocalSettings.php para incluir a nova extensão [1/2]
     shell: echo '#iFrame' >> /var/www/html/LocalSettings.php
     become: yes
   - name: Modidifica o LocalSettings.php para incluir a nova extensão [2/2]
     shell: echo 'wfLoadExtension("iFrame");' >> /var/www/html/LocalSettings.php
     become: yes
   - name: Clona o repositório Git do Interactive Timeline na pasta extensions do MediaWiki
     shell: git clone https://github.com/TheWatcher/InteractiveTimeline.git /var/www/html/extensions/InteractiveTimeline
     become: yes
   - name: Modidifica o LocalSettings.php para incluir a nova extensão [1/2]
     shell: echo '#Interactive Timeline' >> /var/www/html/LocalSettings.php
     become: yes
   - name: Modidifica o LocalSettings.php para incluir a nova extensão [2/2]
     shell: echo 'wfLoadExtension("InteractiveTimeline");' >> /var/www/html/LocalSettings.php
     become: yes
